name: Test Docker Image build

on:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab
    - uses: actions/setup-python@57ded4d7d5e986d7296eab16560982c6dd7c923b
      with:
        python-version: '3.10'

    - name: Set up QEMU
      uses: docker/setup-qemu-action@2b82ce82d56a2a04d2637cd93a637ae1b359c0a7

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@4b4e9c3e2d4531116a6f8ba8e71fc6e2cb6e6c8c

    - name: Build and push
      uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
      with:
        context: .
        push: false
        tags: |
            ghcr.io/repository-service-tuf/repository-service-tuf-worker:test
        build-args: |
          RELEASE_VERSION=test
